version: '3.8'

services:
  frontend:
    build: ./frontend
    networks:
      - app-network
    restart: unless-stopped

  admin_frontend:
    build: ./AdminPanel
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8081:8081"
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - admin_frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
